# constants.py

ERROR_COLOR = "<span style='color: red;'>"
SUCCESS_COLOR = "<span style='color: green;'>"
GENERATED_IMAGES_DIR = 'generated_images'
API_TOKEN_ENV_VAR = "REPLICATE_API_TOKEN"
TIMESTAMP_FORMAT = "%Y%m%d_%H%M%S"
SLIDER_STEPS_MIN = 1
SLIDER_STEPS_MAX = 50
SLIDER_STEPS_DEFAULT = 25
SLIDER_GUIDANCE_MIN = 2
SLIDER_GUIDANCE_MAX = 5
SLIDER_GUIDANCE_STEP = 0.1
SLIDER_GUIDANCE_DEFAULT = 3
SLIDER_SAFETY_MIN = 1
SLIDER_SAFETY_MAX = 5
SLIDER_SAFETY_DEFAULT = 2
SLIDER_INTERVAL_MIN = 1
SLIDER_INTERVAL_MAX = 4
SLIDER_INTERVAL_STEP = 0.1
SLIDER_INTERVAL_DEFAULT = 2
SEED_MAX_VALUE = 4294967295
